# Generated by Django 3.2.3 on 2021-07-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('v_content', models.CharField(max_length=255)),
                ('v_cover', models.CharField(max_length=255)),
                ('sild_image', models.CharField(max_length=255)),
            ],
        ),
    ]
