# Generated by Django 3.2.3 on 2021-07-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='sild_image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='v_cover',
        ),
        migrations.AddField(
            model_name='video',
            name='audio_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='v_content',
            field=models.FileField(upload_to='lecture_video'),
        ),
    ]
