# Generated by Django 3.2.3 on 2021-08-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_rename_v_content_video_v_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='v_info',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
